# Generated by Django 3.2.13 on 2022-07-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partie', to='english_test.joueur'),
        ),
    ]
