# Generated by Django 3.2.13 on 2022-07-11 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0002_alter_partie_joueur'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='creatime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
