# Generated by Django 3.2.13 on 2022-07-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0003_partie_creatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='english_test.partie'),
        ),
    ]
