# Generated by Django 3.2.13 on 2022-07-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0004_alter_question_partie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='creatime',
        ),
    ]
