# Generated by Django 3.2.13 on 2022-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0005_remove_partie_creatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_reponse',
            field=models.DateTimeField(null=True),
        ),
    ]
